name: Deploy to VPS

on:
  push:
    branches:
      - main   # Auto deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run SSH commands on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/silver
            git pull origin main
            npm install --legacy-peer-deps
            npx prisma generate
            npm run build
            pm2 restart jewelry-app

